# This is the configuration file for creating the datasets
# Parameters as the crop size, stride and scale are model specific, so they are defined when calling the model and not here

#Pathsa
train_path: /mnt/0eafdae2-1d8c-43b3-aa1a-2eac4df4bfc5/data/qfastMRI/Train/
val_path: /mnt/0eafdae2-1d8c-43b3-aa1a-2eac4df4bfc5/data/qfastMRI/Val/
tst_path: /mnt/0eafdae2-1d8c-43b3-aa1a-2eac4df4bfc5/data/qfastMRI/Test/ # Test
calib_path: /mnt/0eafdae2-1d8c-43b3-aa1a-2eac4df4bfc5/data/qfastMRI/Test/ # Test
h5f_path: /mnt/0eafdae2-1d8c-43b3-aa1a-2eac4df4bfc5/data/qfastMRI/

#Configuration
augmentation: True

# Other methods TODO

